### ISSUE TITLE
clone ENS onto xdai

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/contracts#104]

**Comment by colourful-land** [comment]
Why is this issue in "contracts"? Sounds like an ios/android feature.

**Comment by James-Sangalli** [comment]
Nope, it is a contract that can be deployed on any eth network, therefore it counts as contracts and is not app specific

**Comment by James-Sangalli** [comment]
https://blockscout.com/poa/dai/address/0x17734f3709486b1d7015f941c069cebf8017a833/transactions
