### ISSUE TITLE
Peter's tool MagicLink with price, transaction fail

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/contracts#118]
Link from Peter's tool, Ropsten
https://app.awallet.io/AgAEk-BceIovS-BDv3l0CkLma9r-RtsoXeTRvANTRzIwMjAwMTAxMDkyNjA3KzA4MDAAC0NhdCAxAAAAMR7BsA6t8Ri2Ivf_XF_4SKbX4qNhhFP4PZa4Ag88jwT0NeT0yERVD8PaHo1lJiiEZe2il-rEZ3eZrcUj73KFFakb

**Comment by James-Sangalli** [comment]
@zhangzhongnan928 this should have been solved in this PR: https://github.com/AlphaWallet/contracts/pull/119 please try again with a new contract from the token factory and close if it is working.

**Comment by zhangzhongnan928** [comment]
Yes, works all good on iOS now
