### ISSUE TITLE
(有方案) Manage the layout of information section (iframe) for tokens.

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/contracts#38]
Need to be able to define what icons and fields to show in asset cards and whether they come with a corresponding image or not (e.g. cryptokitties has image icons) 

- Handle image formats e.g. svg
- Handle different URL formats, e.g. http://img1, ...img2 vs http://img/{id}

**Comment by JamesSmartCell** [comment]
Have we investigated about cryptokitty art copyright issues? Is it legal to download the kitty assets and recompose them?

**Comment by hboon** [comment]
The image is already the composite kitty e.g. https://img.cn.cryptokitties.co/0x06012c8cf97bead5deae237070f9587f8e7a266d/800058.svg

and this is their stand: https://medium.com/cryptokitties/i-want-to-start-out-by-thanking-greg-for-writing-this-post-d306c7a4067f

**Comment by colourful-land** [comment]
> and this is their stand: https://medium.com/cryptokitties/i-want-to-start-out-by-thanking-greg-for-writing-this-post-d306c7a4067f

I use English as a working language since 30 years old - what is their stand? For or against copyrighting crypto kitties?

**Comment by colourful-land** [comment]
Using entirely SVG for the presentation was an idea I had since the start - to be honest I believe in the future it is more graphics than the layout for the limited space on mobile and javascript manipulated SVG seem to be maturing. But (me) not being good at XSLT put a stop in that thinking. I still wish to dive a bit into this direction. How good are you at XSLT master @hboon

**Comment by hboon** [comment]
>> and this is their stand: https://medium.com/cryptokitties/i-want-to-start-out-by-thanking-greg-for-writing-this-post-d306c7a4067f

> I use English as a working language since 30 years old - what is their stand? For or against copyrighting crypto kitties?

Sounds to me they are happy with people using the images (in an undefined limited way) and for the kitty owners to own them, but notably they haven't updated their ToS to say this yet https://www.cryptokitties.co/terms-of-use

**Comment by hboon** [comment]
> But (me) not being good at XSLT put a stop in that thinking. I still wish to dive a bit into this direction. How good are you at XSLT master @hboon

I worked with a gigantic stylesheet many years ago. I haven't used XSLT for a long time so I have forgotten most if not all of it (it's probably for the best), but we can look at it if need be. Is that where we want to go?

Is the idea for the issuers to write stylesheets to lay out the fields? If so, that still doesn't give it much dynamism if what they want is dapps.

**Comment by colourful-land** [comment]
@hboon  Have a look at https://github.com/AlphaWallet/contracts/tree/layout

That's what I am attempting for now.

**Comment by miang719** [comment]
@JamesSmartCell u can continue discuss here
we need this close this issue by 31oct, and continue stage 2.
Lets work it. @James-Sangalli @JamesSmartCell 
@hboon @colourful-land
