### ISSUE TITLE
add `spawned()` function to Spawnable tokens

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/contracts#59]
`spawned(byte32 token_id)` returns a boolean whether the spawnable is spawned.

Rationale:

In order to check if a magic link is redeemed, one only need to check if the owner mentioned in the magic link still have the token in the mentioned magic link.

However spawnable tokens have no owner until they are spawned, therefore it is not possible to look up if it is redeemed in that fashion.

One way to do that is to maintain a list of token_ids that are spawned and return it through this interface.

**Comment by miang719** [comment]
@colourful-land @James-Sangalli can you check the pr?
