### ISSUE TITLE
(有工具) find a XML edit that can edit the HTML components in the XML file

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/contracts#62]
**PREPARE THE TEST FILES**

First, download these 3 files into a folder:

    $ curl -O http://www.w3.org/MarkUp/SCHEMA/xhtml11.xsd
    $ curl -O http://www.w3.org/MarkUp/SCHEMA/xhtml11-model-1.xsd
    $ curl -O http://www.w3.org/MarkUp/SCHEMA/xhtml11-modules-1.xsd

Then save the following in a file `book.xml`:

    <?xml version="1.0"?>
    <lib:library xmlns:lib="http://dyomedea.com/ns/library"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://dyomedea.com/ns/library library.xsd"
          xmlns="http://www.w3.org/1999/xhtml">
      <lib:book id="b0836217462" available="yes">
        <lib:isbn>
          0836217462
        </lib:isbn>
        <lib:title>
          Being a Dog Is a Full-Time Job
        </lib:title>
        <lib:summary>
        <blockquote><p>This book <em>is</em> about a <strong>dog</strong>.</p></blockquote>
        </lib:summary>
      </lib:book>
    </lib:library>

Then save the following in a file `library.xsd`:

    <?xml version="1.0"?>
    <xs:schema targetNamespace="http://dyomedea.com/ns/library"
      elementFormDefault="qualified" attributeFormDefault="unqualified"
      xmlns:xs="http://www.w3.org/2001/XMLSchema"
      xmlns="http://dyomedea.com/ns/library"
                  xmlns:xh="http://www.w3.org/1999/xhtml">
      <xs:import namespace="http://www.w3.org/1999/xhtml"
        schemaLocation="xhtml11.xsd"/>
      <xs:element name="library">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="book" type="bookType"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:complexType name="bookType">
        <xs:sequence>
          <xs:element name="isbn" type="xs:NMTOKEN"/>
          <xs:element name="title" type="xs:string"/>
          <xs:element name="summary" type="xh:xhtml.div.type"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="available" type="xs:string" use="required"/>
      </xs:complexType>
    </xs:schema>

Then make sure everything up to this point is done correctly:

    $ xmllint --schema library.xsd book.xml --noout 
    book.xml validates

The command output "validates" means the test files are prepared 100% correctly.

**CHECK AVAILABLE TOOLS**

Check if you have an XML edit that can edit the `<summary>` section.

Anything that is allowed in `<div>` tag in HTML is allowed in `<summary>` tag.

e.g. you can change the existing summary:

    <p>This book is about a dog.</p>

Into this: `<p>This book <em>is</em> about a dog.</p>`

Or: `<p>This book is about a <strong>dog</strong>.</p>`

Or: `<blockquote><p>This book is about a dog.</p></blockquote>`

**EVALUATE RESULTS**

An idea XML editor recognises that the section is HTML and therefore offers HTML elements to be used there, allows one select "dog" and apply `<strong>` tag on it (offer hints on applicable elements), and renders it correctly.

A "good-enough" XML does only one of them: automatically giving a hint what elements are allowed or renders it visually the way HTML defines it.

**Comment by colourful-land** [comment]
Just in case the XML editor being tested has a type reference bug, this alternative `library.xsd` might be tested:

    <?xml version="1.0"?>
    <xs:schema targetNamespace="http://dyomedea.com/ns/library"
      elementFormDefault="qualified" attributeFormDefault="unqualified"
      xmlns:xs="http://www.w3.org/2001/XMLSchema"
      xmlns="http://dyomedea.com/ns/library"
                  xmlns:xh="http://www.w3.org/1999/xhtml">
      <xs:import namespace="http://www.w3.org/1999/xhtml"
        schemaLocation="xhtml11.xsd"/>
      <xs:element name="library">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="book" type="bookType"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:complexType name="htmlType">
        <xs:sequence>
          <xs:any namespace="http://www.w3.org/1999/xhtml"
            processContents="skip" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
      </xs:complexType>
      <xs:complexType name="bookType">
        <xs:sequence>
          <xs:element name="isbn" type="xs:NMTOKEN"/>
          <xs:element name="title" type="xs:string"/>
          <xs:element name="summary" type="htmlType"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="available" type="xs:string" use="required"/>
      </xs:complexType>
    </xs:schema>

It would also allow the said `book.xml` pass the `xmllint` validation and it has the same effect as the previous version but uses a different mechanism.

**Comment by farrahfazirah** [comment]
I'm using Sublime text to edit the XML file and it works perfectly using the primary library.

<img width="1280" alt="screen shot 2018-10-23 at 3 36 23 pm" src="https://user-images.githubusercontent.com/20555752/47343886-ab995480-d6d9-11e8-9d90-c262f004e37f.png">

I tested a bunch of (commonly used) HTML elements and only `<br>` doesn't work.

This is the HTML that I tested with:

`<?xml version="1.0"?>
<lib:library xmlns:lib="http://dyomedea.com/ns/library"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://dyomedea.com/ns/library library.xsd"
      xmlns="http://www.w3.org/1999/xhtml">
  <lib:book id="b0836217462" available="yes">
    <lib:isbn>
      <div style="margin: 50px;">0836217462</div>
    </lib:isbn>
    <lib:title>
      <div style="margin: 50px;">Being a Dog Is a Full-Time Job</div>
    </lib:title>
    <lib:summary>
      <div style="margin: 50px">
      <p>This book <em>is</em> about a dog.</p>
      <p>This book is about a <strong>dog</strong>.</p>
      <blockquote><p>This book is about a dog.</p></blockquote></div>
    <blockquote><div style="background-color: #000; color: #fff; padding: 50px; margin: 50px;"><p>This book <em>is</em> about a dog.</p></div></blockquote>
    </lib:summary>
  </lib:book>
</lib:library>`

**Comment by colourful-land** [comment]
I forgot to mention the resulting XML must validate - that puts the requirements to the XML editor that it must learn about the structure of the XML from the library.xsd schema

**Comment by farrahfazirah** [comment]
I tested a few XML editors and found this one to be the most ideal:

Oxygen XML Editor
https://www.oxygenxml.com/

<img width="843" alt="screen shot 2018-10-28 at 8 49 13 pm" src="https://user-images.githubusercontent.com/20555752/47616088-eabd1080-daf2-11e8-8237-bc320961d2b8.png">

- Recognises that the section is HTML and highlights HTML attributes
- It shows a list of HTML attributes when user clicks on, for e.g. <strong>dog</strong>. I believe the user can select on which text they want to apply the HTML attribute but I couldn't do it. Perhaps, users can only do it in the paid version?

<img width="855" alt="screen shot 2018-10-28 at 8 48 20 pm" src="https://user-images.githubusercontent.com/20555752/47616095-fe687700-daf2-11e8-8573-5c25ea0efc17.png">

- Visually renders the HTML defined (as shown above).

- Also, fast validation/invalidation

**Comment by colourful-land** [comment]
Very good, that look like what we should use. They have a few products.

If Oxygen XML Author can do the work, we don't need to ask customers to buy Oxygen XML Editor. They are listed here:
https://www.oxygenxml.com/buy.html

Also, would the subscription-based web-author work for our partners?

https://www.oxygenxml.com/xml_web_author/buy_oxygen_xml_web_author.html

That's the last bit then we can close this. Thanks

**Comment by farrahfazirah** [comment]
Oxygen XML Author will suffice. It has imperative features that we need like the HTML view renderer and highlighted HTML attributes.

https://www.oxygenxml.com/subscription_author.html

The subscription-based pricing above is reasonable for our partners.

**Comment by bootingman** [comment]
For your infomation
https://en.wikipedia.org/wiki/Comparison_of_XML_editors
