### ISSUE TITLE
XML should include ABI

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/contracts#70]
Let's examine closer the design requirement of ABI in XML. There are 3 requirements.

**First**, since there are no practical means to obtain ABI from the blockchain nodes, the information in TBML should be a superset of ABI. That means it must be possible to derive the function signature as-is.

For an example function `foo(uint256 tokenID[], string note)` the corresponding TBML should allow the reproduction of the signature:

    foo(uint256[],string)

This would require, as an exmaple, `enum` in TBML to contain not only the way to refer to its value but also the size of value (the size of the member-set), since it would be translated to some type of uint in the signature.

**Second**, it should be possible to produce one binary dataset following the ABI from the sources of data indicated by the XML, that is the value to be used in conformation to the ABI should have references.

The first and second requirement can be done by including, separately, as a combination of *a)* signature as-is and *b)* the data references. However, that would not allow us to achieve the last design requirement:

**Third**, A valid TBML must unambiguously guide the app to produce an accurate binary dataset following the ABI. If it can't, the TBML shouldn't pass validation.

This last design requirement can't be accomplished by including the function signature and a data set matching it in separate parts of a TBML file. So, for example, the following design will not work:

    <signature>foo(uint256[],string)</signature>
    <inputs>
        <uint256 multiple="multiple" ref="assets.tokenIDs">tokenID</uint256>
        <string ref="form.note">note</string>
    </inputs>

Because if you swap the `<string>` and `<uint256>` tag, the schema validator will not detect an error.

It's worth noting that whatever markup that can fully describe a piece of data set satisfying an ABI doesn't necessarily provide enough information to reconstruct that ABI. For example, a piece of data can satisfy ABI interface `uint256[2]` and `(uint256, uint256)` at the same time. Therefore one can't deduct from data the ABI interface. This problem is evident in the JSON representation of data conforming to an ABI,  as one can conclude himself by reading the spec†. TBML must provide enough information to restore a single possible function signature. In other words, it can't copy JSON.

† https://solidity.readthedocs.io/en/develop/abi-spec.html

**Comment by colourful-land** [comment]
Please file this again in Peter's Tools (which is for creating XML file)
https://github.com/lyhistory

**Comment by colourful-land** [comment]
I can file it for you but then it will be under my name.

**Comment by hboon** [comment]
What a coincidence. GitHub has just released a beta feature for transferring issues to another repo a few days ago. You can see it at the bottom right corner of this page "Transfer this issue".

Unfortunately it wouldn't work for this particular case because an issue in a repo owned by an organisation can only be transferred to a repo that is also owned by the same organisation.

**Comment by colourful-land** [comment]
@hboon  will make good use of the new feature. thanks.

Boon:

> The parser we are using in iOS doesn't have `textContent()` and the library we use requires us to pass in the function name and arg types (and return type) separately, but this format can be parsed, so it's not an issue.

Further, regarding return type:

> As long as we are prepared to include a way to explicitly specify a return type later, if necessary — which we should be able to, just use the implicit rules unless the return type is explicitly specified — this sounds good too. I haven't gone through the entire list of Solidity types, but there's a lingering thought that maybe something like the (Ethereum) `Address` or arrays might be an issue (or maybe not).

**Comment by colourful-land** [comment]
This one would satisfy the design requirements:

    <function name="foo" contract="holding">
    <inputs>
        <uint256 multiple="multiple" ref="assets.tokenIDs">tokenID</uint256>
        <string ref="form.note">note</string>
    </inputs>
    </function>

Because the app is able to calculate the signature `foo(uint256[],string)` from the supplied data references.

**Comment by hboon** [comment]
1. Should the value of `<uint256>` here be named differently:

```
    <function name="foo" contract="holding">
        <inputs>
            <uint256 multiple="multiple" ref="assets.tokenIDs">tokenID</uint256>
            <string ref="form.note">note</string>
        </inputs>
    </function>
```

i.e. if it is provided, a special symbol like `each` be used instead:

```
    <function name="foo" contract="holding">
        <inputs>
            <uint256 multiple="multiple" ref="assets.tokenIDs">each</uint256>
            <string ref="form.note">note</string>
        </inputs>
    </function>
```

Can still work as you originally described if it's omitted:

```
    <function name="foo" contract="holding">
        <inputs>
            <uint256 multiple="multiple" ref="assets.tokenIDs"/>
            <string ref="form.note">note</string>
        </inputs>
    </function>
```

I'm presuming `assets` is a JavaScript-like array which contains tokenIDs elements. Then the benefit of `each` is we can potentionally have things like:

```
    <uint256 multiple="multiple" ref="assets.tokenIDs">each.uppercased</uint256>
```

or:

```
    <uint256 multiple="multiple" ref="assets.tokenIDs">each.uppercased()</uint256>
```

referencing this idiom:

```
    assets.tokenIDs.map { each in
        return each.somePropertyOrFunctionOfEach
    }
```

But after writing this, I suppose `tokenID` is derived from dropping the `s` in `tokenIDs`. Same logic maybe :)

2. And following the same line of thought, the `note` value has to be either `each` (a bit strange) or omitted. Because the second `note` in `form.note.note` might be a property/function?

```
    <function name="foo" contract="holding">
        <inputs>
            <uint256 multiple="multiple" ref="assets.tokenIDs">each</uint256>
            <string ref="form.note">note</string>
        </inputs>
    </function>
```

3. Alternatively, since you mention `jq`, there's also the syntax used by the utility https://stedolan.github.io/jq/tutorial/ which attaches meaning to `tokenIDs`, `tokenIDs[]` and `tokenIDs[0]` which can be useful here.

4.

> The second issue is how to select the value from the return values, when the return value can be a tuple. This is perhpas more of an issue in events since functions habitually return just one thing (if you need multiple, call multiple functions) but we can't rule out structs' prevalence as function return values (a struct is a tuple in ABI).

There's a good example of this from CryptoKitties:

```
    function getKitty(uint256 _id)
        external
        view
        returns (
        bool isGestating,
        bool isReady,
        uint256 cooldownIndex,
        uint256 nextActionAt,
        uint256 siringWithId,
        uint256 birthTime,
        uint256 matronId,
        uint256 sireId,
        uint256 generation,
        uint256 genes
    ) {
```

Maybe we can have an attribute based on a `<function>` that captures this.

```
    <attribute-type id="someCompositeThatIsHidden"...>...</attribute-type> 
    <attribute-value ref="someCompositeThatIsHidden"> 
    <function name="getKitty" contract="holding">
        <inputs>
            <uint256 ref="tokenID"/>
        </inputs>
    </function>
```

And then other attributes can refer to the otherwise hidden attribute and extract the desired value(s):

```
    <attribute-type id="isReady"...>...</attribute-type> 
    <attribute-value ref="isReady"> 
    <somethingGoesHere ref="someCompositeThatIsHidden.isReady">
    </>
```

This avoids duplicated function calls.

**Comment by hboon** [comment]
@colourful-land are we placing `<origin>` completely with `<value-sourcing>`?

Both are in MeetupContract.xml, with slight differences:

```
<tb:attribute-type id="locality" oid="2.5.4.7" syntax="1.3.6.1.4.1.1466.115.121.1.15">
  <tb:name lang="en">City</tb:name>
  <tb:name lang="zh">城市</tb:name>
  <tb:origin contract="holding-contract">
    <tb:function name="getLocality">
      <tb:inputs>
        <tb:uint256 ref="tokenID"/>
      </tb:inputs>
    </tb:function>
  </tb:origin>
</tb:attribute-type>
```

and:

```
<tb:attribute-type id="expired" syntax="1.3.6.1.4.1.1466.115.121.1.7"> <!-- boolean -->
  <tb:value-sourcing>
    <tb:function contract="holding-contract" name="isExpired">
      <tb:inputs>
        <tb:uint256 ref="tokenID"/>
      </tb:inputs>
    </tb:function>
  </tb:value-sourcing>
</tb:attribute-type>
```

**Comment by colourful-land** [comment]
Compare this:

    <attribute-type ref="locality">
     <name>....</name>
     <origin>
      <bitmask bitmask="00000000000000000000000000000000FF000000000000000000000\
000000000" as="mapping">
         <option key="1"> <value lang="en">Moscow</value> </option>
         <option key="2"> <value lang="en">Saint Petersburg</value> </option>
         <option key="3"> <value lang="en">Sochi</value> </option>
         <option key="4"> <value lang="en">Ekaterinburg</value> </option>
         <option key="5"> <value lang="en">Saransk</value> </option>
         <option key="6"> <value lang="en">Kazan</value> </option>
         <option key="7"> <value lang="en">Nizhny Novgorod</value> </option>
         <option key="8"> <value lang="en">Rostov-on-Don</value> </option>
         <option key="9"> <value lang="en">Samara</value> </option>
         <option key="10"> <value lang="en">Volgograd</value> </option>
         <option key="11"> <value lang="en">Kaliningrad</value> </option>
      </bitmask>
      <event contract="holding" name="relocation" value="l">
         <filter></filter> 
      </event>
      <function contract="holding"
                name="getLocality"> 
         <inputs><uint256 ref="tokenID"/></inputs>
      </function>
      <script contract="holding" ref="getl">
        <inputs><uint256 ref="tokenID"/></inputs>
      </script>
     </origin>
    </attribute-type>

With this:

    <attribute-type ref="locality">
     <name>....</name>
     <origin bitmask="00000000000000000000000000000000FF00000000000000000000000\
0000000" as="mapping">
       <mapping>
         <option key="1"> <value lang="en">Moscow</value> </option>
         <option key="2"> <value lang="en">Saint Petersburg</value> </option>
         <option key="3"> <value lang="en">Sochi</value> </option>
         <option key="4"> <value lang="en">Ekaterinburg</value> </option>
         <option key="5"> <value lang="en">Saransk</value> </option>
         <option key="6"> <value lang="en">Kazan</value> </option>
         <option key="7"> <value lang="en">Nizhny Novgorod</value> </option>
         <option key="8"> <value lang="en">Rostov-on-Don</value> </option>
         <option key="9"> <value lang="en">Samara</value> </option>
         <option key="10"> <value lang="en">Volgograd</value> </option>
         <option key="11"> <value lang="en">Kaliningrad</value> </option>
       </mapping>
      </bitmask>
     <origin contract="holding" as="value">
      <event name="relocation" value="l">
         <filter></filter> 
      </event>
      <function name="getLocality"> 
         <inputs><uint256 ref="tokenID"/></inputs>
      </function>
      <script ref="getl">
        <inputs><uint256 ref="tokenID"/></inputs>
      </script>
     </origin>
    </attribute-type>

The latter has the advantage that the return value in a smart-contract
can be picked up as a mapping source, which is needed for localisation
(since it is generally believed that smart contract isn't responsible
of localisation or storage of look-up table). However, it might break
your use-case

**Comment by colourful-land** [comment]
Compare this:

    <attribute-type ref="locality">
     <name>....</name>
     <origin>
      <bitmask bitmask="00000000000000000000000000000000FF000000000000000000000\
000000000" as="mapping">
         <option key="1"> <value lang="en">Moscow</value> </option>
         <option key="2"> <value lang="en">Saint Petersburg</value> </option>
         <option key="3"> <value lang="en">Sochi</value> </option>
         <option key="4"> <value lang="en">Ekaterinburg</value> </option>
         <option key="5"> <value lang="en">Saransk</value> </option>
         <option key="6"> <value lang="en">Kazan</value> </option>
         <option key="7"> <value lang="en">Nizhny Novgorod</value> </option>
         <option key="8"> <value lang="en">Rostov-on-Don</value> </option>
         <option key="9"> <value lang="en">Samara</value> </option>
         <option key="10"> <value lang="en">Volgograd</value> </option>
         <option key="11"> <value lang="en">Kaliningrad</value> </option>
      </bitmask>
      <event contract="holding" name="relocation" value="l">
         <filter></filter> 
      </event>
      <function contract="holding"
                name="getLocality"> 
         <inputs><uint256 ref="tokenID"/></inputs>
      </function>
      <script contract="holding" ref="getl">
        <inputs><uint256 ref="tokenID"/></inputs>
      </script>
     </origin>
    </attribute-type>

With this:

    <attribute-type ref="locality">
     <name>....</name>
     <origin bitmask="00000000000000000000000000000000FF00000000000000000000000\
0000000" as="mapping">
       <mapping>
         <option key="1"> <value lang="en">Moscow</value> </option>
         <option key="2"> <value lang="en">Saint Petersburg</value> </option>
         <option key="3"> <value lang="en">Sochi</value> </option>
         <option key="4"> <value lang="en">Ekaterinburg</value> </option>
         <option key="5"> <value lang="en">Saransk</value> </option>
         <option key="6"> <value lang="en">Kazan</value> </option>
         <option key="7"> <value lang="en">Nizhny Novgorod</value> </option>
         <option key="8"> <value lang="en">Rostov-on-Don</value> </option>
         <option key="9"> <value lang="en">Samara</value> </option>
         <option key="10"> <value lang="en">Volgograd</value> </option>
         <option key="11"> <value lang="en">Kaliningrad</value> </option>
       </mapping>
      </bitmask>
     <origin contract="holding" as="value">
      <event name="relocation" value="l">
         <filter></filter> 
      </event>
      <function name="getLocality"> 
         <inputs><uint256 ref="tokenID"/></inputs>
      </function>
      <script ref="getl">
        <inputs><uint256 ref="tokenID"/></inputs>
      </script>
     </origin>
    </attribute-type>

The latter has the advantage that the return value in a smart-contract can be picked up as a mapping source, which is needed for localisation since it is commonly accepted that smart contract doesn't do localisation nor does it store look-up table. However, it might break your use-case of `someCompositeThatIsHidden`

**Comment by hboon** [comment]
The latter seems better. We can implement reading a property from a composite with something like this?

Capture the composite attribute like normal:

```
<attribute-type ref="someCompositeThatIsHidden">
    <name>....</name>
    <origin .. />
    <origin .. />
    <origin .. />
    </origin>
</attribute-type>
```

Read a property with the composite as an origin:

```
<attribute-type ref="isReady">
    <name>....</name>
    <origin>
        <from-attribute ref="someCompositeThatIsHidden">
            <attribute-value ref="isReady"> 
        </from-attribute>
    </origin>
</attribute-type>
```

Is that what you were referring to?
