### ISSUE TITLE
two issues identified in function encodeMessageSpawnable

### ISSUE THREAD

**Issue by lyhistory** [AlphaWallet/contracts#74]
last few days I was struggling with redemption of the MagicLink generated by Peter's Tool, after times of failure, I found the issues, need to confirm with @James-Sangalli  the encoding standard for Spawnable Message:

1. the first point here isn't an issue, just that I remembered there was a discussion about adding leading byte to indicate the type of tokens, I guess the final decision is add specific functions for spawnable token instead of leading byte, so I have removed the leading byte from the MagicLink to conform with current standard, please confirm

2. First issue: is that I find the code has invert the sequence of the TokenID 

`
function encodeMessageSpawnable(uint value, uint expiry, uint256[] tickets)
internal view returns (bytes32)
(....ignore....)
for (i = 0; i < tickets.length; i++)
        {
            message[84 + i * 32 ] = byte(tickets[i]);
            // convert uint256[] to bytes
            for (uint j = 1; j < 32; j++)
            {
                message[84 + i * 32 + j] = byte(tickets[i] = tickets[i] >> 8);
            }
        }
        return keccak256(message);`

I tested this MagicLink
https://app.awallet.io/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAXAANACM92snd1ZrM0nV1-WgiVHdk1oqzOjIwMTgxMTMwMDAwMDAwKzA4MDAAAQAAVklQAABBLTHbHCp4qQMhjGkRq6JnSxHQi4Rip-Hv4eSD6lmphAXMYzJ3vYnb0hTJaa6aw2PbuR8Q0YGf9eUh8TuwdbpDTL2FGw==
it contains only one ticket(32 bytes)
and the tokenID is:
In BigInteger: 26322820181848127205119429488744061657188852288741917040354512141634951523633
In Bytes:
0 = 58  1 = 50  2 = 48  3 = 49  4 = 56  5 = 49  6 = 49  7 = 51  8 = 48  9 = 48  10 = 48  11 = 48  12 = 48  13 = 48  14 = 48  15 = 43  16 = 48  17 = 56  18 = 48  19 = 48  20 = 0  21 = 1  22 = 0  23 = 0  24 = 86  25 = 73  26 = 80  27 = 0  28 = 0  29 = 65  30 = 45  31 = 49
if use your method, the result is inversion of original bytes:
 0 = 49  1 = 45  2 = 65  3 = 0  4 = 0  5 = 80  6 = 73  7 = 86  8 = 0  9 = 0  10 = 1  11 = 0  12 = 48  13 = 48  14 = 56  15 = 48  16 = 43  17 = 48  18 = 48  19 = 48  20 = 48  21 = 48  22 = 48  23 = 48  24 = 51  25 = 49  26 = 49  27 = 56  28 = 49  29 = 48  30 = 50  31 = 58

so I changed the method to:
`
for (i = 0; i < tickets.length; i++)
        {
            message[84 + i * 32 +31] = byte(tickets[i]);
            // convert uint256[] to bytes
            for (uint j = 1; j < 32; j++)
            {
                message[84 + i * 32 + 31 - j] = byte(tickets[i] = tickets[i] >> 8);
            }
        }
`
and redeemed it successfully

3. Second issue: 
`
function spawnPassTo(uint256 expiry,
                    uint256[] tickets,
                    uint8 v,
                    bytes32 r,
                    bytes32 s,
                    address recipient) public
    {
       (....ignore....)
        bytes32 message = encodeMessageSpawnable(0, expiry, tickets);
        (....ignore....)
        for(uint i = 0; i < tickets.length; i++)
        {
            inventory[recipient].push(tickets[i]);
	    spawnedTickets.push(tickets[i]);
        }
    }`
the expected data pushed to inventory and spawnedTickets by right should be 26322820181848127205119429488744061657188852288741917040354512141634951523633, but actually it become '58', so I add a temp variable _tickets in encodeMessageSpawnable, and then it works
`
uint256[] memory _tickets=new uint256[](tickets.length);
        for (i = 0; i < tickets.length; i++)
        {
            _tickets[i]=tickets[i];
            message[84 + i * 32 +31] = byte(tickets[i]);
            // convert uint256[] to bytes
            for (uint j = 1; j < 32; j++)
            {
                message[84 + i * 32 + 31 - j] = byte(tickets[i] = tickets[i] >> 8);
            }
        }
        for(i=0; i< _tickets.length;i++){
          tickets[i] = _tickets[i];
        }
`

**Comment by lyhistory** [comment]
because I'm not familiar with solidity, maybe I did something stupid, please correct me,
and  finally I have successfully tested through the whole workflow,
from generating MagicLink to parse MagicLink and call smart contract to redeem the token, and then verify the token status (call the new added Spawned function to check if a spawnable ticket that created in a magic link is redeemed)

**Comment by James-Sangalli** [comment]
@lyhistory 
1) we do use an encoding byte
2) I think this is a solidity bug that reverses the order, good spotting
3) Not sure why this is?

**Comment by lyhistory** [comment]
hi, I'm in in Great of wall of china, will be back on Thursday, now I'm VPC to my laptop in singapore to reply you :)
1.you mean we use leading byte for Spawnable token? but in your encodeMessageSpawnable, I could not see the leading byte, I have to remove the leading byte in Peter's tool so that the ecrecover can give correct result
2. really, that's cool
3. let me explain this, in my local env, in order to debug the MeetupContract, I added some more functions to query the data pushed to the mapping variables, and I found that:
in your function spawnPassTo, after all the require assert, you will push tickets to inventory inventory[recipient].push(tickets[i]); 
and when I query the content of the data pushed to the inventory, 
take example of this token 26322820181848127205119429488744061657188852288741917040354512141634951523633
the real data pushed to inventory is actually the first byte which is 0 = 58
that's why I add that temporary variable and it works by pushing the correct biginteger into inventory and my new added spawnedTickets array
function spawnPassTo(uint256 expiry, uint256[] tickets, uint8 v, bytes32 r, bytes32 s, address recipient) public 
{ (....ignore....) 
bytes32 message = encodeMessageSpawnable(0, expiry, tickets); 
(....ignore....) 
for(uint i = 0; i < tickets.length; i++) { 
inventory[recipient].push(tickets[i]); 
spawnedTickets.push(tickets[i]); } 
}

**Comment by James-Sangalli** [comment]
@lyhistory the extra byte is dropped off by the app, the app checks the byte, takes it off and calls the appropriate function. It is not supposed to sign that extra byte. Sorry if this was not clear from the beginning.

**Comment by James-Sangalli** [comment]
New contract is out and is working with transfers and links

**Comment by lyhistory** [comment]
@James-Sangalli 
sorry for reopening this issue, the last one still unsolved, I wrote a test you can check it from here
https://ethfiddle.com/GutzmufJUm
and I also tested on remix get the same result
as you can see, the value of the tickets has been changed after calling encodeMessageSpawnable(tickets)

![1](https://user-images.githubusercontent.com/1522513/48265518-aa04b600-e467-11e8-8552-d267a711e5f2.png)
![2](https://user-images.githubusercontent.com/1522513/48265534-af620080-e467-11e8-979e-127dc7bd45d9.png)

**Comment by James-Sangalli** [comment]
@lyhistory, encodeMessageSpawnable is shifting the bits by 8 each loop, therefore you are left with only the first 2 bytes after giving it over.

            message[i * 32 + j] = byte(bytes32(tickets[i] = tickets[i] << 8));

This shifts the bits by 8, by the end of the loop you are left with only the last byte in the original variable.

Does this clarify your understanding?

**Comment by lyhistory** [comment]
hi, @James-Sangalli 
according to what we talked over wechat last time, about that we should store the unchanged original variable instead of shifted one,
should I commit my patches for the last issue or you will fix it?

**Comment by James-Sangalli** [comment]
@lyhistory please do.

**Comment by lyhistory** [comment]
ok, will commit it later
