### ISSUE TITLE
issues about new MeetupContract.xml

### ISSUE THREAD

**Issue by lyhistory** [AlphaWallet/contracts#92]
@colourful-land 
1. country and time overlap 1 byte, is it wrong?
![image](https://user-images.githubusercontent.com/1522513/48756090-acbaa300-ecd2-11e8-980b-1003500acd34.png)

>compare to the previous version
![image](https://user-images.githubusercontent.com/1522513/48756014-767d2380-ecd2-11e8-942e-33e357b1861b.png)

2. not sure how country and locality works now?
as I see you have removed options for country&locality(city), don't know how to render it in peter's tool, just one textbox for user to keyin?
and locality(city) now is a function, how I include city info into 32 bytes

**Comment by colourful-land** [comment]
2. Locality is now read from the smart contract. As a result, it's not localised. It's not perfect this way but we can use this to delay lookup table editing function for a while. You simply don't render it for now. It should be supplied at the time the contract was deployed. Do not render any value that is sourced from the smart contract - we will put that to a later milestone.

3. Can you help to correct the overlapping bit by shifting bits lower? e.g. maybe we can afford to lose a byte in `category` or `section`? -- you can do a pull request.
